In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_zero_d = tf.constant(1)
print(tensor_zero_d)

tf.Tensor(1, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [4]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
    ])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],
    [[10,0,2],
     [1,0,2]],
    [[5,8,0],
     [2,7,0]],
    [[2,1,9],
     [4,-3,32]]
    ])
print(tensor_three_d)
print("Shape",tensor_three_d.shape)
print("Dimension",tensor_three_d.ndim)
print("Data Type",tensor_three_d.dtype)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  0  2]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
Shape (4, 2, 3)
Dimension 3
Data Type <dtype: 'int32'>


In [6]:
tensor_four_d = tf.constant([
    [
    [[1,2,0],
    [3,5,-1]],
    [[10,0,2],
     [1,0,2]],
    [[5,8,0],
     [2,7,0]],
    [[2,1,9],
     [4,-3,32]]
     ],
    [
    [[0,2,5],
    [5,3,1]],
    [[0,2,0],
     [-1,10,0]],
    [[0,5,1],
     [1,7,0]],
    [[3,8,7],
     [3,2,2]]
     ],
    [
    [[4,5,4],
    [3,1,1]],
    [[0,2,5],
     [0,4,3]],
    [[3,4,2],
     [5,8,3]],
    [[8,2,5],
     [2,3,3]]
     ],
     ])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  0  2]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 0  2  5]
   [ 5  3  1]]

  [[ 0  2  0]
   [-1 10  0]]

  [[ 0  5  1]
   [ 1  7  0]]

  [[ 3  8  7]
   [ 3  2  2]]]


 [[[ 4  5  4]
   [ 3  1  1]]

  [[ 0  2  5]
   [ 0  4  3]]

  [[ 3  4  2]
   [ 5  8  3]]

  [[ 8  2  5]
   [ 2  3  3]]]], shape=(3, 4, 2, 3), dtype=int32)


In [7]:
tensor_one_d = tf.constant([2.3,0,-3], dtype=tf.float16)
print(tensor_one_d)

tf.Tensor([ 2.3  0.  -3. ], shape=(3,), dtype=float16)


In [8]:
c_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.float16)
print(c_tensor_one_d)

tf.Tensor([ 2.3  0.  -3. ], shape=(3,), dtype=float16)


In [9]:
x_np = np.array([3,4,5])
x_np

array([3, 4, 5])

In [10]:
x_tf = tf.convert_to_tensor(x_np, dtype=tf.float16)
x_tf

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([3., 4., 5.], dtype=float16)>

In [11]:
identity_matrix = tf.eye(num_rows=2,num_columns=3,batch_shape=[3])
identity_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 1., 0.]],

       [[1., 0., 0.],
        [0., 1., 0.]],

       [[1., 0., 0.],
        [0., 1., 0.]]], dtype=float32)>

In [12]:
fill_Tensor = tf.fill([2,3],9)
fill_Tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [13]:
ones_tensor = tf.ones([2,3])
ones_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [14]:
zeroes_tensor = tf.zeros([2,3])
zeroes_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [15]:
ones_like_tensor = tf.ones_like(tensor_four_d)
ones_like_tensor

<tf.Tensor: shape=(3, 4, 2, 3), dtype=int32, numpy=
array([[[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]]])>

In [16]:
range_tensor = tf.range(start=2, limit=10, delta=2)
range_tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8])>

In [17]:
tf.shape(range_tensor)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4])>

In [18]:
tf.size(range_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [19]:
g = tf.random.Generator.from_non_deterministic_state()
g.normal(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.2545965 , -1.2422496 , -0.05050273],
       [ 1.1684766 , -0.0026021 , -0.13619329]], dtype=float32)>

In [20]:
g = tf.random.Generator.from_seed(123)
g.normal(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.8673864 , -0.29899067, -0.9310337 ],
       [-1.5828488 ,  1.2481191 , -0.6770643 ]], dtype=float32)>

In [21]:
g = tf.random.Generator.from_seed(123)
g.uniform(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.65647066, 0.30283117, 0.18523741],
       [0.5846225 , 0.36490846, 0.3291067 ]], dtype=float32)>

In [22]:
g = tf.random.Generator.from_seed(123)
g.normal(shape=(2, 3), mean=0., stddev=1.0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.8673864 , -0.29899067, -0.9310337 ],
       [-1.5828488 ,  1.2481191 , -0.6770643 ]], dtype=float32)>

In [23]:
g = tf.random.Generator.from_seed(123)
g.uniform(shape=(2, 3), minval=0, maxval=100)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[65.647064, 30.283117, 18.52374 ],
       [58.46225 , 36.490845, 32.910667]], dtype=float32)>

In [24]:
normal_tensor = tf.random.normal((3,2),mean=0.0, stddev=0.05, seed=None)
normal_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.09481047, -0.0424097 ],
       [ 0.01854984,  0.07641087],
       [-0.02177913,  0.01085432]], dtype=float32)>

In [25]:
normal_tensor = tf.random.uniform((3,2),minval=0.0, maxval=0.05, seed=None)
normal_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.02573587, 0.00300751],
       [0.04530696, 0.04639232],
       [0.04955447, 0.04326447]], dtype=float32)>

In [26]:
tensor_index = tf.constant([3,6,2,4,6,66,7])
print(tensor_index)
print(tensor_index[1:4])
print(tensor_index[1:])
print(tensor_index[1:6:2])
print(tensor_index[1:-1])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([6 2 4], shape=(3,), dtype=int32)
tf.Tensor([ 6  2  4  6 66  7], shape=(6,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)
tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)


In [27]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8],
])

print(tensor_two_d)
print(tensor_two_d[0:3,0:2])
print(tensor_two_d[0:3,:])
print(tensor_two_d[2,:])
print(tensor_two_d[2,0])
print(tensor_two_d[:,0])
print(tensor_two_d[...,2])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)
tf.Tensor([1 5 6], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)
tf.Tensor([ 0 -1  6  8], shape=(4,), dtype=int32)


In [28]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],
    [[10,0,2],
     [1,0,2]],
    [[5,8,0],
     [2,7,0]],
    [[2,1,9],
     [4,-3,32]]
    ])

print(tensor_three_d[0,:,:])
print(tensor_three_d[0,0,:])
print(tensor_three_d[0,:,-1])
print(tensor_three_d[0:2,:,-1])
print(tensor_three_d[...,:,2])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2 0], shape=(3,), dtype=int32)
tf.Tensor([ 0 -1], shape=(2,), dtype=int32)
tf.Tensor(
[[ 0 -1]
 [ 2  2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -1]
 [ 2  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)


In [29]:
tf.abs(tf.constant(-10))

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [30]:
tf.abs(tf.constant([-2.25+4.75j]))

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [31]:
tf.sqrt(tf.constant([4.]))

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.], dtype=float32)>

In [32]:
x_1 = tf.constant([2,1,5], dtype=tf.float32)
x_2 = tf.constant([2,0,5],dtype=tf.float32)

print(tf.add(x_1,x_2) )
print(tf.multiply(x_1,x_2)) 
print(tf.subtract(x_1,x_2)) 
print(tf.divide(x_1,x_2)) 
print(tf.math.divide_no_nan(x_1,x_2)) 

tf.Tensor([ 4.  1. 10.], shape=(3,), dtype=float32)
tf.Tensor([ 4.  0. 25.], shape=(3,), dtype=float32)
tf.Tensor([0. 1. 0.], shape=(3,), dtype=float32)
tf.Tensor([ 1. inf  1.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 1.], shape=(3,), dtype=float32)


In [33]:
x_1 = tf.constant([2,1,5,12,4,5,6], dtype=tf.float32)
x_2 = tf.constant([7],dtype=tf.float32)

print(tf.add(x_1,x_2) )

tf.Tensor([ 9.  8. 12. 19. 11. 12. 13.], shape=(7,), dtype=float32)


In [34]:
print(tf.maximum(3,5))
print(tf.minimum(3,5))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [35]:
x = [1,23,4,100]

print(tf.argmax(x))
print(tf.argmin(x))

tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


In [36]:
x = tf.constant(tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,60],
    [2,3,8]
    ]))

print(tf.argmax(x, axis=0))
print(tf.argmin(x, axis=0))
print(tf.argmax(x, axis=1))
print(tf.argmin(x, axis=1))

tf.Tensor([1 1 2], shape=(3,), dtype=int64)
tf.Tensor([0 0 1], shape=(3,), dtype=int64)
tf.Tensor([1 1 2 2], shape=(4,), dtype=int64)
tf.Tensor([2 2 0 0], shape=(4,), dtype=int64)


In [37]:
print(tf.equal([3,2],[2,4]))
print(tf.equal([3,2],[2]))

tf.Tensor([False False], shape=(2,), dtype=bool)
tf.Tensor([False  True], shape=(2,), dtype=bool)


In [38]:
print(tf.pow([2,3],[2,3]))
print(tf.pow([2,3],[2]))

tf.Tensor([ 4 27], shape=(2,), dtype=int32)
tf.Tensor([4 9], shape=(2,), dtype=int32)


In [39]:
x = tf.constant(tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,60],
    [2,3,8]
    ]))

print(tf.reduce_sum(x, axis=0))
print(tf.reduce_sum(x, axis=1))

tf.Tensor([ 7 15 67], shape=(3,), dtype=int32)
tf.Tensor([ 3  7 66 13], shape=(4,), dtype=int32)


In [40]:
print(tf.reduce_max(x, axis=0))
print(tf.reduce_max(x, axis=1))

tf.Tensor([ 3  5 60], shape=(3,), dtype=int32)
tf.Tensor([ 2  5 60  8], shape=(4,), dtype=int32)


In [41]:
print(tf.reduce_mean(x, axis=0))
print(tf.reduce_mean(x, axis=1))

tf.Tensor([ 1  3 16], shape=(3,), dtype=int32)
tf.Tensor([ 1  2 22  4], shape=(4,), dtype=int32)


In [42]:
tf.reduce_sum(x, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 7, 15, 67]])>

In [43]:
tf.math.top_k(x, k=2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 2,  1],
       [ 5,  3],
       [60,  5],
       [ 8,  3]])>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [2, 1],
       [2, 1]])>)

In [44]:
x_1 = tf.constant([[1,2,0],[3,5,-1]])
x_2 = tf.constant([[1,2,0],[3,5,-1], [4,5,6]])

tf.linalg.matmul(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]])>

In [45]:
x_1 @ x_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  7,  12,  -2],
       [ 14,  26, -11]])>

In [46]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]])>

In [47]:
tf.linalg.matmul(x_1,x_2,transpose_a=False, transpose_b=True,adjoint_a=False, adjoint_b=False)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5, 13, 14],
       [13, 35, 31]])>

In [48]:
x_1 = tf.constant([
    [[1,0],
    [3,-1]],
    [[10,2],
     [1,2]],
    [[5,0],
     [2,0]],
    [[2,9],
     [4,32]]
    ])
x_2 = tf.constant([
    [[1,2,0],
    [3,5,-1]],
    [[10,0,2],
     [1,0,2]],
    [[5,8,0],
     [2,7,0]],
    [[2,1,9],
     [4,-3,32]]
    ])

tf.linalg.matmul(x_1, x_2)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[   1,    2,    0],
        [   0,    1,    1]],

       [[ 102,    0,   24],
        [  12,    0,    6]],

       [[  25,   40,    0],
        [  10,   16,    0]],

       [[  40,  -25,  306],
        [ 136,  -92, 1060]]])>

In [49]:
tensor_two_d = tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8]
    ])

print(tf.linalg.band_part(tensor_two_d, 0, 0))
print(tf.linalg.band_part(tensor_two_d, -1, 0))
print(tf.linalg.band_part(tensor_two_d, 0, -1))

tf.Tensor(
[[1 0 0]
 [0 5 0]
 [0 0 6]
 [0 0 0]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[1 0 0]
 [3 5 0]
 [1 5 6]
 [2 3 8]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[  1  -2   0]
 [  0   5 100]
 [  0   0   6]
 [  0   0   0]], shape=(4, 3), dtype=int32)


In [50]:
x = tf.constant([[1,2],[3,4]], dtype=tf.float32)

x_inv  = tf.linalg.inv(x)

x @ x_inv

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.0000000e+00,  0.0000000e+00],
       [-4.7683716e-07,  1.0000002e+00]], dtype=float32)>

In [51]:
s,u,v = tf.linalg.svd(x)

print(s)
print(u)
print(v)

tf.Tensor([5.4649854  0.36596614], shape=(2,), dtype=float32)
tf.Tensor(
[[ 0.4045535 -0.9145143]
 [ 0.9145143  0.4045535]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.5760484  0.8174156]
 [ 0.8174156 -0.5760484]], shape=(2, 2), dtype=float32)


In [52]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0],
              ])

B = np.array([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5],
])

print(A.shape)
print(B.shape)

print("AxB =",np.matmul(A,B))
print("Einsum", np.einsum("ij,jk -> ik", A,B))

(3, 4)
(4, 5)
AxB = [[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]
Einsum [[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [53]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0],
              ])

B = np.array([
    [2,9,0,3],
    [3,6,8,-2],
    [1,3,5,0],
])

print(A.shape)
print(B.shape)

print("AxB =",A*B)
print("Einsum", np.einsum("ij,ij -> ij", A,B))

(3, 4)
(3, 4)
AxB = [[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]
Einsum [[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [54]:
A = np.array([[2,6,5,2],
              [2,-2,2,3],
              [1,5,4,0],
              ])

print("Transponse = ", A.T)
print("Einsum", np.einsum("ij -> ji",A))

Transponse =  [[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]
Einsum [[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [55]:
A = np.array([
    [
        [2,6,5,2],
        [2,-2,2,3],
        [1,5,4,0]
    ],
    [
        [1,3,1,22],
        [0,2,2,0],
        [1,5,4,1]
    ]
])

B = np.array([
    [
        [2,0,0,3,0],
        [3,6,8,-2,2],
        [1,3,5,0,1],
        [3,0,2,0,5],
    ],
    [
        [1,0,0,3,0],
        [3,0,4,-2,2],
        [1,0,2,0,0],
        [3,0,1,1,0],
    ]
])

print(A.shape, B.shape)

print("AxB =",np.matmul(A,B))
print("Einsum", np.einsum("bij,bjk -> bik", A,B))

(2, 3, 4) (2, 4, 5)
AxB = [[[33 51 77 -6 27]
  [ 9 -6  0 10 13]
  [21 42 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]
Einsum [[[33 51 77 -6 27]
  [ 9 -6  0 10 13]
  [21 42 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [56]:
A = np.array([
    [
        [2,6,5,2],
        [2,-2,2,3],
        [1,5,4,0]
    ],
    [
        [1,3,1,22],
        [0,2,2,0],
        [1,5,4,1]
    ]
])

print("Sum =", np.sum(A))
print("Einsum", np.einsum("bij-> ", A))

Sum = 72
Einsum 72


In [57]:
A = np.array(
    [
        [2,6,5,2],
        [2,-2,2,3],
        [1,5,4,0]
    ], 
)

print("Sum =", np.sum(A, axis=0))
print("Einsum", np.einsum("ij -> j ", A))

print("Sum =", np.sum(A, axis=1))
print("Einsum", np.einsum("ij-> i ", A))

Sum = [ 5  9 11  5]
Einsum [ 5  9 11  5]
Sum = [15  5 10]
Einsum [15  5 10]


In [58]:
Q = np.random.randn(32,64,512)
k = np.random.randn(32,128,512)

In [59]:
np.einsum("bqm,bkm -> bqk",Q,k).shape

(32, 64, 128)

In [60]:
A = np.random.randn(2,4,4,2)
B = np.random.randn(2,4,4,1)

In [61]:
np.einsum("bcik, bcij -> bckj", B,A).shape

(2, 4, 1, 2)

In [4]:
a = tf.constant([1,3,4,5,6,7])
print(a.shape)

(6,)


(<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 3, 4, 5, 6, 7]])>,
 <tf.Tensor: shape=(6, 1), dtype=int32, numpy=
 array([[1],
        [3],
        [4],
        [5],
        [6],
        [7]])>)

In [5]:
print(tf.expand_dims(a, axis=0))
print(tf.expand_dims(a, axis=1))

tf.Tensor([[1 3 4 5 6 7]], shape=(1, 6), dtype=int32)
tf.Tensor(
[[1]
 [3]
 [4]
 [5]
 [6]
 [7]], shape=(6, 1), dtype=int32)


In [9]:
A = tf.constant([
    [
        [2,6,5,2],
        [2,-2,2,3],
        [1,5,4,0]
    ],
    [
        [1,3,1,22],
        [0,2,2,0],
        [1,5,4,1]
    ]
])
print(A.shape)
tf.expand_dims(A, axis=0)

(2, 3, 4)


<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
array([[[[ 2,  6,  5,  2],
         [ 2, -2,  2,  3],
         [ 1,  5,  4,  0]],

        [[ 1,  3,  1, 22],
         [ 0,  2,  2,  0],
         [ 1,  5,  4,  1]]]])>

In [12]:
c = tf.expand_dims(A, axis=-1)
print(c.shape)

print(tf.squeeze(c, axis=-1).shape)

(2, 3, 4, 1)
(2, 3, 4)


In [15]:
a = tf.constant([1,2,3,4,5,6,7,8,9])

print(tf.reshape(a, [3,3]))
print(tf.reshape(a, [3,-1]))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [19]:
t1 = tf.constant([[1,2,3], [4,5,6]])
print(t1.shape)

tf.reshape(t1, [6])

(2, 3)


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [24]:
t1 = tf.constant([[1,2,3], [4,5,6]])
t2 = tf.constant([[7,8,9], [10,11,12]])

print(tf.concat([t1,t2], axis=0))
print(tf.concat([t1,t2], axis=1))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [26]:
t1 = [[1, 2, 3],
      [4, 5, 6],
      [5, 6, 2],
      [1, 2, 1]]

t2 = [[7, 8, 9],
      [10, 11, 12],
      [0, 0, 2],
      [-1, 5, 2]]

tf.concat([t1, t2], axis = 0)

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  2],
       [ 1,  2,  1],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 0,  0,  2],
       [-1,  5,  2]])>

In [30]:
t1 = tf.constant([[1,2,3], [4,5,6]])
t2 = tf.constant([[7,8,9], [10,11,12]])

print(tf.stack([t1, t2], axis=0))
print(tf.stack([t1, t2], axis=-1))
print(tf.concat([t1, t2], axis=0))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


In [38]:
t = tf.constant([[1,2,3], [4,5,6]])
# paddings = tf.constant([[1,1], [2,4]])
paddings = tf.constant([[4,1], [2,4]])

print(tf.pad(t,paddings, "CONSTANT"))
print(tf.pad(t,paddings, "CONSTANT", constant_values=9))

tf.Tensor(
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0 0 0]
 [0 0 4 5 6 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]], shape=(7, 9), dtype=int32)
tf.Tensor(
[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 1 2 3 9 9 9 9]
 [9 9 4 5 6 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]], shape=(7, 9), dtype=int32)


In [39]:
a = tf.constant([4,5,6,7])

a[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6])>

In [40]:
tf.gather(a, [0,3,1], axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 7, 5])>

In [53]:
b = [[7, 8, 9],
      [10, 11, 12],
      [1, 0, 2],
      [-1, 5, 2]]

print(tf.gather(b, [3,0], axis=0))
print(tf.gather(b, [2,0], axis=1))

tf.Tensor(
[[-1  5  2]
 [ 7  8  9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 9  7]
 [12 10]
 [ 2  1]
 [ 2 -1]], shape=(4, 2), dtype=int32)


In [51]:
print(tf.gather(b, [[3,0], [2,0]], axis=0))

tf.Tensor(
[[[-1  5  2]
  [ 7  8  9]]

 [[ 0  0  2]
  [ 7  8  9]]], shape=(2, 2, 3), dtype=int32)


In [55]:
print(tf.gather_nd(b, [[3,0],[2,0]]))
print(tf.gather_nd(b, [[3],[2]]))

tf.Tensor([-1  1], shape=(2,), dtype=int32)
tf.Tensor(
[[-1  5  2]
 [ 1  0  2]], shape=(2, 3), dtype=int32)


In [64]:
x = [
    [1,2,0],
    [3],
    [1,5,6,5,6],
    [2,3],
]

ragged_tensor = tf.ragged.constant(x)
ragged_tensor.shape, ragged_tensor

(TensorShape([4, None]),
 <tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>)

In [65]:
tf.RaggedTensor.from_row_lengths(
    values=[3,1,4,1,5,9,2,6],
    row_lengths=[4,0,3,1,0]
)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>

In [70]:
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[1,1],[3,4]], values=[11,56], dense_shape=[5,6]
)
sparse_tensor


SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

In [71]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]])>

In [72]:
tensor_string = tf.constant(["Hello", "I am", "String"])

tensor_string

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'Hello', b'I am', b'String'], dtype=object)>

In [74]:
tf.strings.join(tensor_string, separator=' ')

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello I am String'>

In [77]:
x_var = tf.Variable([1,2], name="var1")
x_var

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [79]:
x_var.assign([2,1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 1])>

In [82]:
x_var.assign_add([1,1])

(<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 2])>,
 <tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 2])>)

In [83]:
x_var.assign_sub([1,1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 1])>

In [88]:
with tf.device('CPU:0'):
    x_var = tf.Variable(0.2)
    x = tf.constant(0.2)

x_var.device, x.device

('/job:localhost/replica:0/task:0/device:CPU:0',
 '/job:localhost/replica:0/task:0/device:CPU:0')

In [89]:
with tf.device('CPU:0'):
    x_1 = tf.constant(0.2)
    x_2 = tf.constant(0.2)

with tf.device('GPU:0'):
    x_3 = x_1 + x_2

print(x_1.device,x_1)
print(x_2.device,x_2)
print(x_3.device,x_3)

/job:localhost/replica:0/task:0/device:CPU:0 tf.Tensor(0.2, shape=(), dtype=float32)
/job:localhost/replica:0/task:0/device:CPU:0 tf.Tensor(0.2, shape=(), dtype=float32)
/job:localhost/replica:0/task:0/device:CPU:0 tf.Tensor(0.4, shape=(), dtype=float32)
